server:
  address: 0.0.0.0
  port: 8080
springdoc:
  api-docs:
    path: /api-documentation
  remove-broken-reference-definitions: false
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: airportsDB
      username: user
      password: pass
      authentication-database: admin