server:
  address: 0.0.0.0
  port: 8080
springdoc:
  api-docs:
    path: /api-documentation
  remove-broken-reference-definitions: false
spring:
  data:
    cassandra:
      keyspace-name: airports
      contact-points: 127.0.0.1
      port: 9042
