server:
  address: 0.0.0.0
  port: 8080
springdoc:
  api-docs:
    path: /api-documentation
  remove-broken-reference-definitions: false
spring:
  data:
    cassandra:
      keyspace-name: ${CASSANDRA_KEYSPACE:airports}
      contact-points: ${CASSANDRA_CONTACT:localhost}
      port: ${CASSANDRA_PORT:9042}
      schema-action: ${CASSANDRA_SCHEMA_ACTION:recreate}
      username: ${CASSANDRA_USER:cassandra}
      password: ${CASSANDRA_PASSWORD:pass}
      local-datacenter: ${CASSANDRA_DC:datacenter1}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  kafka:
    consumer:
      auto-offset-reset: earliest
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
cassandraConfig: production
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.apache.kafka: WARN
management:
  endpoints:
    web:
      base-path: "/actuator/prometheus"
      exposure:
        include: health,info,metrics,prometheus
