version: '3'
services: 
  generating-service:
    image: dominikoman16/task1
    ports:
      - "8080:8080"
    environment:
      - CASSANDRA_CONTACT=cassandra
    restart: always
    depends_on:
      - cassandra
    links:
      - cassandra
  handling-service:
    image: dominikoman16/task2
    ports:
      - "9090:9090"
    command:
      --generating.url="http://generating-service:8080/"
    depends_on:
      - generating-service
    links:
      - generating-service
  cassandra:
#create keyspace!!!
#CREATE KEYSPACE airports with replication={'class':'NetworkTopologyStrategy', 'replication_factor':3};
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
