version: '3'
services: 
  generating-service:
    image: dominikoman16/task1
    ports:
      - "8080:8080"
    environment:
      - CASSANDRA_CONTACT=cassandra
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - cassandra
    links:
      - cassandra
  handling-service:
    image: dominikoman16/task2
    ports:
      - "9090:9090"
    command:
      --generating.url="http://generating-service:8080/"
    depends_on:
      - generating-service
    links:
      - generating-service
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
