#mongo
#helm install cassandra --set dbUser.password=pass,dbUser.user=cassandra,persistence.size=1Gi,replicaCount=3 bitnami/cassandra
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generating-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: generator
  template:
    metadata:
      labels:
        component: generator
    spec: 
      containers:
        - name: generating
          image: dominikoman16/task1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: CASSANDRA_KEYSPACE
              value: "airports"
            - name: CASSANDRA_CONTACT
              value: "cassandra"
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_SCHEMA_ACTION
              value: "create_if_not_exists"
            - name: CASSANDRA_USER
              value: "cassandra"
            - name: CASSANDRA_PASSWORD
              value: "pass"
            - name: CASSANDRA_DC
              value: "DC1"