version: '3'
services:
  generating-data:
    build:
      context: .
    container_name: task1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - CASSANDRA_CONTACT=cassandra
    links:
      - cassandra
    depends_on:
      - cassandra
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"


