version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
  generating-data:
    build: .
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongodb:mongodb
volumes:
  data: {}

