version: '3'
services:
  generating-data:
    build:
      context: .
    container_name: task1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - CASSANDRA_CONTACT=cassandra
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - cassandra
    depends_on:
      - cassandra
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

#  CREATE KEYSPACE airports with replication={'class':'NetworkTopologyStrategy', 'replication_factor':3};