version: '3'
services:
  generating-data:
    image: dominikoman16/task1
    container_name: task1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - CASSANDRA_KEYSPACE=airports
      - CASSANDRA_CONTACT=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_SCHEMA_ACTION=create_if_not_exists


