server:
  address: 0.0.0.0
  port: 9090
springdoc:
  api-docs.path: /api-documentation
  remove-broken-reference-definitions: false
spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.apache.kafka: OFF